// DO NOT EDIT: Autogenerated file created on 2024-03-08 4:08:05 PM. 
using System;
using System.Linq;
using System.Collections.Generic;
using Ara3D.Parakeet.Grammars;

namespace Ara3D.Parakeet.Cst.CombinatorCalculusGrammarNameSpace
{
    public class CstNodeFactory : INodeFactory
    {
        public static CombinatorCalculusGrammar StaticGrammar = CombinatorCalculusGrammar.Instance;
        public IGrammar Grammar { get; } = StaticGrammar;
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "Application": return new CstApplication(node.Children.Select(Create).ToArray());
                case "Combinator": return new CstCombinator(node.Contents);
                case "Identifier": return new CstIdentifier(node.Contents);
                case "Term": return new CstTerm(node.Children.Select(Create).ToArray());
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
