// DO NOT EDIT: Autogenerated file created on 2024-03-04 7:41:43 PM. 
using System;
using System.Linq;
using System.Collections.Generic;
using Ara3D.Parakeet.Grammars;

namespace Ara3D.Parakeet.Cst.CsvGrammarNameSpace
{
    public class CstNodeFactory : INodeFactory
    {
        public static CsvGrammar StaticGrammar = CsvGrammar.Instance;
        public IGrammar Grammar { get; } = StaticGrammar;
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "Field": return new CstField(node.Children.Select(Create).ToArray());
                case "File": return new CstFile(node.Children.Select(Create).ToArray());
                case "Identifier": return new CstIdentifier(node.Contents);
                case "Row": return new CstRow(node.Children.Select(Create).ToArray());
                case "String": return new CstString(node.Contents);
                case "Text": return new CstText(node.Contents);
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
