// DO NOT EDIT: Autogenerated file created on 2026-07-07 4:05:55 PM. 
using System;
using System.Linq;

namespace Ara3D.Parakeet.Cst.JoyGrammarNameSpace
{
    /// <summary>This interface exists to make it easy to auto-generate type switches</summary>
    public interface IJoyCstNode { }

    /// <summary>
    /// Rule = Def ::= (Symbol('DEFINE')+Operator+(Spaces)?+Symbol('==')+((Expr+(Spaces)?))*+'.')
    /// Nodes = (Operator+(Expr)*)
    /// </summary>
    public class CstDef : CstNodeSequence, IJoyCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Def;
        public CstDef(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstOperator> Operator => new CstNodeFilter<CstOperator> (Children);
        public CstNodeFilter<CstExpr> Expr => new CstNodeFilter<CstExpr> (Children);
    }

    /// <summary>
    /// Rule = Expr ::= ((Quotation+(Spaces)?)|(Literal+(Spaces)?)|(Operator+(Spaces)?)|(Identifier+(Spaces)?))
    /// Nodes = (Quotation|Literal|Operator|Identifier)
    /// </summary>
    public class CstExpr : CstNodeChoice, IJoyCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Expr;
        public CstExpr(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstQuotation> Quotation => new CstNodeFilter<CstQuotation> (Children);
        public CstNodeFilter<CstLiteral> Literal => new CstNodeFilter<CstLiteral> (Children);
        public CstNodeFilter<CstOperator> Operator => new CstNodeFilter<CstOperator> (Children);
        public CstNodeFilter<CstIdentifier> Identifier => new CstNodeFilter<CstIdentifier> (Children);
    }

    /// <summary>
    /// Rule = Identifier ::= (IdentifierFirstChar+(IdentifierChar)*)
    /// Nodes = 
    /// </summary>
    public class CstIdentifier : CstNodeLeaf, IJoyCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Identifier;
        public CstIdentifier(ILocation location, string text) : base(location, text) { }
    }

    /// <summary>
    /// Rule = Literal ::= (Float|Integer|DoubleQuoteBasicString)
    /// Nodes = 
    /// </summary>
    public class CstLiteral : CstNodeLeaf, IJoyCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Literal;
        public CstLiteral(ILocation location, string text) : base(location, text) { }
    }

    /// <summary>
    /// Rule = Operator ::= (([\x21$-\x26\x2A+\x2D\x2F<->\x40^|~])*|(Identifier+(Spaces)?))
    /// Nodes = 
    /// </summary>
    public class CstOperator : CstNodeLeaf, IJoyCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Operator;
        public CstOperator(ILocation location, string text) : base(location, text) { }
    }

    /// <summary>
    /// Rule = Quotation ::= (Symbol('[')+((Expr+(Spaces)?))*+Symbol(']'))
    /// Nodes = (Expr)*
    /// </summary>
    public class CstQuotation : CstNode, IJoyCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Quotation;
        public CstQuotation(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstExpr> Expr => new CstNodeFilter<CstExpr> (Children);
    }

}
