// DO NOT EDIT: Autogenerated file created on 2024-03-02 8:35:34 AM. 
using System;
using System.Linq;

namespace Ara3D.Parakeet.Cst.JsonGrammarNameSpace
{
    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstArray : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Array;
        public CstArray(string text) : base(text) { }
        // No children
    }

    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstConstant : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Constant;
        public CstConstant(string text) : base(text) { }
        // No children
    }

    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstIdentifier : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Identifier;
        public CstIdentifier(string text) : base(text) { }
        // No children
    }

    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstJson : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Json;
        public CstJson(string text) : base(text) { }
        // No children
    }

    /// <summary>
    /// Nodes = String
    /// </summary>
    public class CstMember : CstNode
    {
        public static Rule Rule = CstNodeFactory.Grammar.Member;
        public CstMember(params CstNode[] children) : base(children) { }
        public CstNodeFilter<CstString> String => new CstNodeFilter<CstString> (Children);
    }

    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstNumber : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Number;
        public CstNumber(string text) : base(text) { }
        // No children
    }

    /// <summary>
    /// Nodes = (Member)*
    /// </summary>
    public class CstObject : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Object;
        public CstObject(string text) : base(text) { }
        public CstNodeFilter<CstMember> Member => new CstNodeFilter<CstMember> (Children);
    }

    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstString : CstNodeLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.String;
        public CstString(string text) : base(text) { }
        // No children
    }

}
