// DO NOT EDIT: Autogenerated file created on 2026-07-07 4:05:55 PM. 
using System;
using System.Linq;

namespace Ara3D.Parakeet.Cst.JsonGrammarNameSpace
{
    /// <summary>This interface exists to make it easy to auto-generate type switches</summary>
    public interface IJsonCstNode { }

    /// <summary>
    /// Rule = Array ::= ('['+_RECOVER_+WS+(Elements)?+WS+']')
    /// Nodes = (Element)*
    /// </summary>
    public class CstArray : CstNode, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Array;
        public CstArray(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstElement> Element => new CstNodeFilter<CstElement> (Children);
    }

    /// <summary>
    /// Rule = Constant ::= (("false"|"true"|"null")+!(IdentifierChar))
    /// Nodes = 
    /// </summary>
    public class CstConstant : CstNodeLeaf, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Constant;
        public CstConstant(ILocation location, string text) : base(location, text) { }
    }

    /// <summary>
    /// Rule = Element ::= ((Object+WS)|(Array+WS)|(String+WS)|(Number+WS)|(Constant+WS))
    /// Nodes = (Object|Array|String|Number|Constant)
    /// </summary>
    public class CstElement : CstNodeChoice, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Element;
        public CstElement(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstObject> Object => new CstNodeFilter<CstObject> (Children);
        public CstNodeFilter<CstArray> Array => new CstNodeFilter<CstArray> (Children);
        public CstNodeFilter<CstString> String => new CstNodeFilter<CstString> (Children);
        public CstNodeFilter<CstNumber> Number => new CstNodeFilter<CstNumber> (Children);
        public CstNodeFilter<CstConstant> Constant => new CstNodeFilter<CstConstant> (Children);
    }

    /// <summary>
    /// Rule = Identifier ::= (IdentifierFirstChar+(IdentifierChar)*)
    /// Nodes = 
    /// </summary>
    public class CstIdentifier : CstNodeLeaf, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Identifier;
        public CstIdentifier(ILocation location, string text) : base(location, text) { }
    }

    /// <summary>
    /// Rule = Json ::= (WS+Element+WS+WS)
    /// Nodes = Element
    /// </summary>
    public class CstJson : CstNode, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Json;
        public CstJson(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstElement> Element => new CstNodeFilter<CstElement> (Children);
    }

    /// <summary>
    /// Rule = Member ::= (String+WS+_RECOVER_+WS+':'+WS+Element+WS)
    /// Nodes = (String+Element)
    /// </summary>
    public class CstMember : CstNodeSequence, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Member;
        public CstMember(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstString> String => new CstNodeFilter<CstString> (Children);
        public CstNodeFilter<CstElement> Element => new CstNodeFilter<CstElement> (Children);
    }

    /// <summary>
    /// Rule = Number ::= (Integer+(Fraction)?+(Exponent)?)
    /// Nodes = 
    /// </summary>
    public class CstNumber : CstNodeLeaf, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Number;
        public CstNumber(ILocation location, string text) : base(location, text) { }
    }

    /// <summary>
    /// Rule = Object ::= ('{'+_RECOVER_+WS+(Members)?+'}')
    /// Nodes = (Member)*
    /// </summary>
    public class CstObject : CstNode, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.Object;
        public CstObject(ILocation location, params CstNode[] children) : base(location, children) { }
        public CstNodeFilter<CstMember> Member => new CstNodeFilter<CstMember> (Children);
    }

    /// <summary>
    /// Rule = String ::= ('"'+_RECOVER_+(StringChar)*+'"')
    /// Nodes = 
    /// </summary>
    public class CstString : CstNodeLeaf, IJsonCstNode
    {
        public static Rule Rule = CstNodeFactory.StaticGrammar.String;
        public CstString(ILocation location, string text) : base(location, text) { }
    }

}
