// DO NOT EDIT: Autogenerated file created on 2024-03-08 4:08:06 PM. 
using System;
using System.Linq;
using System.Collections.Generic;
using Ara3D.Parakeet.Grammars;

namespace Ara3D.Parakeet.Cst.PhoneNumberGrammarNameSpace
{
    public class CstNodeFactory : INodeFactory
    {
        public static PhoneNumberGrammar StaticGrammar = PhoneNumberGrammar.Instance;
        public IGrammar Grammar { get; } = StaticGrammar;
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "AreaCode": return new CstAreaCode(node.Children.Select(Create).ToArray());
                case "AreaCodeDigits": return new CstAreaCodeDigits(node.Contents);
                case "CountryCode": return new CstCountryCode(node.Contents);
                case "Exchange": return new CstExchange(node.Contents);
                case "Identifier": return new CstIdentifier(node.Contents);
                case "PhoneNumber": return new CstPhoneNumber(node.Children.Select(Create).ToArray());
                case "Subscriber": return new CstSubscriber(node.Contents);
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
