// DO NOT EDIT: Autogenerated file created on 2024-03-11 1:16:58 PM. 
using System;
using System.Linq;
using System.Collections.Generic;
using Ara3D.Parakeet.Grammars;

namespace Ara3D.Parakeet.Cst.PlatoTokenGrammarNameSpace
{
    public class CstNodeFactory : INodeFactory
    {
        public static PlatoTokenGrammar StaticGrammar = PlatoTokenGrammar.Instance;
        public IGrammar Grammar { get; } = StaticGrammar;
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "BinaryLiteral": return new CstBinaryLiteral(node.Contents);
                case "BinaryOperator": return new CstBinaryOperator(node.Contents);
                case "BooleanLiteral": return new CstBooleanLiteral(node.Contents);
                case "BracedTokenGroup": return new CstBracedTokenGroup(node.Contents);
                case "BracketedTokenGroup": return new CstBracketedTokenGroup(node.Contents);
                case "CharLiteral": return new CstCharLiteral(node.Contents);
                case "Comment": return new CstComment(node.Contents);
                case "Delimiter": return new CstDelimiter(node.Contents);
                case "FieldName": return new CstFieldName(node.Children.Select(Create).ToArray());
                case "FloatLiteral": return new CstFloatLiteral(node.Contents);
                case "FunctionName": return new CstFunctionName(node.Children.Select(Create).ToArray());
                case "HexLiteral": return new CstHexLiteral(node.Contents);
                case "Identifier": return new CstIdentifier(node.Contents);
                case "IntegerLiteral": return new CstIntegerLiteral(node.Contents);
                case "Literal": return new CstLiteral(node.Children.Select(Create).ToArray());
                case "NullLiteral": return new CstNullLiteral(node.Contents);
                case "Operator": return new CstOperator(node.Contents);
                case "ParameterName": return new CstParameterName(node.Children.Select(Create).ToArray());
                case "ParenthesizedTokenGroup": return new CstParenthesizedTokenGroup(node.Contents);
                case "Separator": return new CstSeparator(node.Children.Select(Create).ToArray());
                case "StatementKeyword": return new CstStatementKeyword(node.Contents);
                case "StringLiteral": return new CstStringLiteral(node.Contents);
                case "TokenGroup": return new CstTokenGroup(node.Children.Select(Create).ToArray());
                case "TypeKeyword": return new CstTypeKeyword(node.Contents);
                case "TypeName": return new CstTypeName(node.Children.Select(Create).ToArray());
                case "TypeParametersToken": return new CstTypeParametersToken(node.Children.Select(Create).ToArray());
                case "TypeParameterToken": return new CstTypeParameterToken(node.Children.Select(Create).ToArray());
                case "Unknown": return new CstUnknown(node.Contents);
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
