// DO NOT EDIT: Autogenerated file created on 2024-03-03 10:34:03 PM. 
using System;
using System.Linq;
using System.Collections.Generic;
using Ara3D.Parakeet.Grammars;

namespace Ara3D.Parakeet.Cst.SExpressionGrammarNameSpace
{
    public class CstNodeFactory : INodeFactory
    {
        public static SExpressionGrammar StaticGrammar = SExpressionGrammar.Instance;
        public IGrammar Grammar { get; } = StaticGrammar;
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "Atom": return new CstAtom(node.Children.Select(Create).ToArray());
                case "Document": return new CstDocument(node.Children.Select(Create).ToArray());
                case "Expr": return new CstExpr(node.Children.Select(Create).ToArray());
                case "Identifier": return new CstIdentifier(node.Contents);
                case "List": return new CstList(node.Children.Select(Create).ToArray());
                case "Symbol": return new CstSymbol(node.Contents);
                case "SymbolWithSpaces": return new CstSymbolWithSpaces(node.Contents);
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
