// DO NOT EDIT: Autogenerated file created on 2024-01-26 1:43:39 AM. 
using System;
using System.Linq;
using Ara3D.Parsing;

namespace Parakeet.Cst.CommonGrammar
{
    /// <summary>
    /// Nodes = 
    /// </summary>
    public class CstIdentifier : CstLeaf
    {
        public static Rule Rule = CstNodeFactory.Grammar.Identifier;
        public CstIdentifier(string text) : base(text) { }
        // No children
    }

}
