// DO NOT EDIT: Autogenerated file created on 2024-01-26 1:43:40 AM. 
using System;
using System.Linq;
using Ara3D.Parsing;
using System.Collections.Generic;

namespace Parakeet.Cst.JsonGrammar
{
    public class CstNodeFactory
    {
        public static Parakeet.Cst.JsonGrammarGrammar Grammar = new Parakeet.Cst.JsonGrammarGrammar();
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "Array": return new CstArray(node.Contents);
                case "Constant": return new CstConstant(node.Contents);
                case "Element": return new CstElement(node.Children.Select(Create).ToArray());
                case "Identifier": return new CstIdentifier(node.Contents);
                case "Json": return new CstJson(node.Children.Select(Create).ToArray());
                case "Member": return new CstMember(node.Children.Select(Create).ToArray());
                case "Number": return new CstNumber(node.Contents);
                case "Object": return new CstObject(node.Contents);
                case "Json": return new CstJson(node.Children.Select(Create).ToArray());
                case "String": return new CstString(node.Contents);
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
